
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: localdisk
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true

---

kind: PersistentVolume
apiVersion: v1
metadata:
 name: my-pv
spec:
 storageClassName: localdisk
 persistentVolumeReclaimPolicy: Recycle
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /var/output

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: my-pvc
spec:
 storageClassName: localdisk
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 100Mi


---

apiVersion: v1
kind: Pod
metadata:
 name: pv-pod
spec:
 #restartPolicy: Never
 containers:
 - name: busybox
   image: busybox
   #command: ['sh', '-c', 'echo Success! > /output/success.txt']
   command: ['sh', '-c', 'while true; do echo Success! > /output/success.txt; sleep 5; done']
   volumeMounts:
   - name: pv-storage
     mountPath: /output
 volumes:
 - name: pv-storage
   persistentVolumeClaim:
    claimName: my-pvc
